### ISSUE TITLE
Throw on explicit quantifier when min > max

### ISSUE THREAD

**Issue by conartist6** [mysticatea/regexpp#21]
This matches the behavior of builtin regex

**Comment by ota-meshi** [comment]
Which API are you using? I think the following source code will throw the error correctly.

```js
parseRegExpLiteral("/a{1,0}/")
// SyntaxError: Invalid regular expression: /a{1,0}/: numbers out of order in {} quantifier
```

**Comment by conartist6** [comment]
To be honest I don't remember anymore. I sure didn't give very much information did I? Let's close this and I'll reopen if I ever figure out what specifically my problem was.
