### ISSUE TITLE
Missing support for js-supported character class

### ISSUE THREAD

**Issue by mattbishop** [mysticatea/regexpp#25]
I want to parse this regex:

`/\p{ID_Start}\p{ID_Continue}+/u`

Node 16 accepts it:

```js
const idRegex = /^\p{ID_Start}\p{ID_Continue}+$/u
console.log(idRegex.test("anIdentifier")
// > true
console.log(idRegex.test("not an Identifier")
// > false
```

regexpp 3.2.0 does not:

```js
regexpp.validateRegExpLiteral(/^\p{ID_Start}\p{ID_Continue}+$/u)
// > RangeError: Invalid code point -1
at Function.fromCodePoint in ECMAScript
at RegExpValidator.validateLiteral in regexpp/index.js — line 411
at Object.validateRegExpLiteral in regexpp/index.js — line 2084

These two character classes are important for programming language parsing: https://unicode.org/reports/tr31/

**Comment by ota-meshi** [comment]
Hi @mattbishop .
`validateRegExpLiteral` accepts string.
I think may you need to do the following:

```js
regexpp.validateRegExpLiteral(/^\p{ID_Start}\p{ID_Continue}+$/u.toString())
```

**Comment by conartist6** [comment]
@mattbishop is this issue resolved?

**Comment by mattbishop** [comment]
I don't think so. No changes to the code have been added for 10 months.

**Comment by conartist6** [comment]
@mattbishop I am able to confirm what ota-meshi said (that there is no bug). See: https://runkit.com/conartist6/624da94f206e790009a8a78b

**Comment by RunDevelopment** [comment]
As document [here](https://github.com/mysticatea/regexpp#-usage) (and [here](https://github.com/mysticatea/regexpp/blob/b8bc4e82885a9cff44b908d247685cde129cd863/src/index.ts#L27)), `validateRegExpLiteral` takes a string as its first argument, not a regex.

**Comment by mattbishop** [comment]
Ah I see now. I thought it could take a RegExp like `parseRegExpLiteral`. I will close this issue but it seems odd that parse takes both string and Regexp while validate only takes string.

Thanks for the clarification!
